# Generated by Django 2.0.13 on 2019-06-09 22:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='类别', max_length=20, unique=True, verbose_name='类别')),
                ('weight', models.IntegerField(blank=True, default=0, help_text='权重', verbose_name='权重')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '类别',
                'verbose_name_plural': '类别',
                'db_table': 'tb_category',
            },
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='网站名称', max_length=50, unique=True, verbose_name='网站名称')),
                ('desc', models.CharField(blank=True, default='', help_text='简介', max_length=200, null=True, verbose_name='简介')),
                ('url', models.URLField(help_text='网站url', max_length=300, verbose_name='网站url')),
                ('logo', models.ImageField(blank=True, max_length=200, null=True, upload_to='logo')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('category', models.ForeignKey(help_text='类别', on_delete=django.db.models.deletion.CASCADE, related_name='website_category', to='arsenal.Category', verbose_name='类别')),
            ],
            options={
                'verbose_name': '网站',
                'verbose_name_plural': '网站',
                'db_table': 'tb_website',
            },
        ),
    ]
