# Generated by Django 2.0.13 on 2019-06-10 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsenal', '0002_category_is_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='weight',
            field=models.IntegerField(blank=True, default=0, help_text='权重', max_length=100, verbose_name='权重'),
        ),
    ]
