# Generated by Django 2.0.13 on 2019-06-10 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsenal', '0003_auto_20190610_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='weight',
            field=models.IntegerField(blank=True, default=0, help_text='权重', verbose_name='权重'),
        ),
    ]
