# Generated by Django 2.0.13 on 2019-06-11 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsenal', '0004_auto_20190610_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sn',
            field=models.CharField(help_text='生成随机英文ID', max_length=20, null=True, verbose_name='生成随机英文ID'),
        ),
    ]
